"""Build pipeline/universe/seed_expansion.csv from curated additions."""
from __future__ import annotations

import csv
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SEED = ROOT / "seed_global.csv"
OUT = ROOT / "seed_expansion.csv"

ADDS: list[tuple[str, str, str]] = [
    # US tech / growth
    ("TSLA", "US", "Tesla Inc"),
    ("NFLX", "US", "Netflix Inc"),
    ("DIS", "US", "Walt Disney Company"),
    ("UBER", "US", "Uber Technologies"),
    ("ABNB", "US", "Airbnb Inc"),
    ("BKNG", "US", "Booking Holdings"),
    ("SHOP", "US", "Shopify Inc"),
    ("SBUX", "US", "Starbucks Corporation"),
    ("CMG", "US", "Chipotle Mexican Grill"),
    ("YUM", "US", "Yum! Brands"),
    ("DPZ", "US", "Dominos Pizza"),
    ("DASH", "US", "DoorDash Inc"),
    ("CRWD", "US", "CrowdStrike Holdings"),
    ("DDOG", "US", "Datadog Inc"),
    ("SNOW", "US", "Snowflake Inc"),
    ("NET", "US", "Cloudflare Inc"),
    ("ZS", "US", "Zscaler Inc"),
    ("OKTA", "US", "Okta Inc"),
    ("TEAM", "US", "Atlassian Corporation"),
    ("WDAY", "US", "Workday Inc"),
    ("MDB", "US", "MongoDB Inc"),
    ("HUBS", "US", "HubSpot Inc"),
    ("TTD", "US", "Trade Desk Inc"),
    ("SPOT", "US", "Spotify Technology"),
    ("EA", "US", "Electronic Arts"),
    ("TTWO", "US", "Take-Two Interactive"),
    ("PLTR", "US", "Palantir Technologies"),
    ("SMCI", "US", "Super Micro Computer"),
    ("ARM", "US", "Arm Holdings ADR"),
    ("MRVL", "US", "Marvell Technology"),
    ("NXPI", "US", "NXP Semiconductors"),
    ("ON", "US", "ON Semiconductor"),
    ("MU", "US", "Micron Technology"),
    ("INTC", "US", "Intel Corporation"),
    ("APH", "US", "Amphenol Corporation"),
    ("TEL", "US", "TE Connectivity"),
    ("GLW", "US", "Corning Inc"),
    ("KEYS", "US", "Keysight Technologies"),
    ("MPWR", "US", "Monolithic Power Systems"),
    ("FSLR", "US", "First Solar"),
    ("ENPH", "US", "Enphase Energy"),
    # US industrials / materials
    ("GE", "US", "GE Aerospace"),
    ("MMM", "US", "3M Company"),
    ("PH", "US", "Parker-Hannifin"),
    ("ROK", "US", "Rockwell Automation"),
    ("DOV", "US", "Dover Corporation"),
    ("XYL", "US", "Xylem Inc"),
    ("TT", "US", "Trane Technologies"),
    ("CARR", "US", "Carrier Global"),
    ("OTIS", "US", "Otis Worldwide"),
    ("JCI", "US", "Johnson Controls"),
    ("IR", "US", "Ingersoll Rand"),
    ("FTV", "US", "Fortive Corporation"),
    ("PWR", "US", "Quanta Services"),
    ("VMC", "US", "Vulcan Materials"),
    ("MLM", "US", "Martin Marietta Materials"),
    ("NUE", "US", "Nucor Corporation"),
    ("FCX", "US", "Freeport-McMoRan"),
    ("NEM", "US", "Newmont Corporation"),
    ("ECL", "US", "Ecolab Inc"),
    ("DD", "US", "DuPont de Nemours"),
    ("PPG", "US", "PPG Industries"),
    ("ALB", "US", "Albemarle Corporation"),
    ("URI", "US", "United Rentals"),
    ("PCAR", "US", "PACCAR Inc"),
    ("GWW", "US", "W.W. Grainger"),
    ("POOL", "US", "Pool Corporation"),
    ("WSO", "US", "Watsco Inc"),
    # US healthcare
    ("PFE", "US", "Pfizer Inc"),
    ("BMY", "US", "Bristol-Myers Squibb"),
    ("MRNA", "US", "Moderna Inc"),
    ("HCA", "US", "HCA Healthcare"),
    ("MCK", "US", "McKesson Corporation"),
    ("CAH", "US", "Cardinal Health"),
    ("COR", "US", "Cencora Inc"),
    ("DGX", "US", "Quest Diagnostics"),
    ("LH", "US", "Labcorp Holdings"),
    ("HOLX", "US", "Hologic Inc"),
    ("ALGN", "US", "Align Technology"),
    ("PODD", "US", "Insulet Corporation"),
    ("WAT", "US", "Waters Corporation"),
    ("ILMN", "US", "Illumina Inc"),
    ("ZBH", "US", "Zimmer Biomet"),
    ("BDX", "US", "Becton Dickinson"),
    ("BAX", "US", "Baxter International"),
    ("STE", "US", "Steris plc"),
    ("ALNY", "US", "Alnylam Pharmaceuticals"),
    ("BMRN", "US", "BioMarin Pharmaceutical"),
    ("ARGX", "US", "argenx ADR"),
    ("GMAB", "US", "Genmab ADR"),
    # US consumer / travel / logistics
    ("TGT", "US", "Target Corporation"),
    ("DG", "US", "Dollar General"),
    ("DLTR", "US", "Dollar Tree"),
    ("BBY", "US", "Best Buy Co"),
    ("EBAY", "US", "eBay Inc"),
    ("EL", "US", "Estee Lauder"),
    ("KHC", "US", "Kraft Heinz"),
    ("GIS", "US", "General Mills"),
    ("HSY", "US", "Hershey Company"),
    ("CHD", "US", "Church & Dwight"),
    ("CLX", "US", "Clorox Company"),
    ("KR", "US", "Kroger Co"),
    ("SYY", "US", "Sysco Corporation"),
    ("MAR", "US", "Marriott International"),
    ("HLT", "US", "Hilton Worldwide"),
    ("EXPE", "US", "Expedia Group"),
    ("RCL", "US", "Royal Caribbean"),
    ("DAL", "US", "Delta Air Lines"),
    ("UAL", "US", "United Airlines"),
    ("FDX", "US", "FedEx Corporation"),
    ("UPS", "US", "United Parcel Service"),
    ("CSX", "US", "CSX Corporation"),
    ("NSC", "US", "Norfolk Southern"),
    ("LEN", "US", "Lennar Corporation"),
    ("DHI", "US", "D.R. Horton"),
    ("PHM", "US", "PulteGroup Inc"),
    ("DRI", "US", "Darden Restaurants"),
    ("WING", "US", "Wingstop Inc"),
    ("CAVA", "US", "CAVA Group"),
    ("QSR", "US", "Restaurant Brands"),
    ("YUMC", "US", "Yum China Holdings"),
    # US utilities / energy
    ("DUK", "US", "Duke Energy"),
    ("SO", "US", "Southern Company"),
    ("D", "US", "Dominion Energy"),
    ("AEP", "US", "American Electric Power"),
    ("EXC", "US", "Exelon Corporation"),
    ("SRE", "US", "Sempra"),
    ("AWK", "US", "American Water Works"),
    ("WMB", "US", "Williams Companies"),
    ("KMI", "US", "Kinder Morgan"),
    ("LNG", "US", "Cheniere Energy"),
    ("SLB", "US", "Schlumberger NV"),
    ("BKR", "US", "Baker Hughes"),
    ("EOG", "US", "EOG Resources"),
    ("COP", "US", "ConocoPhillips"),
    ("FANG", "US", "Diamondback Energy"),
    ("MPC", "US", "Marathon Petroleum"),
    ("VLO", "US", "Valero Energy"),
    # US IT / digital infra / REITs / services
    ("PAYX", "US", "Paychex Inc"),
    ("CTSH", "US", "Cognizant Technology"),
    ("EPAM", "US", "EPAM Systems"),
    ("IT", "US", "Gartner Inc"),
    ("CDW", "US", "CDW Corporation"),
    ("DELL", "US", "Dell Technologies"),
    ("HPQ", "US", "HP Inc"),
    ("NTAP", "US", "NetApp Inc"),
    ("ZM", "US", "Zoom Communications"),
    ("CHKP", "US", "Check Point Software"),
    ("CYBR", "US", "CyberArk Software"),
    ("GEN", "US", "Gen Digital"),
    ("EQIX", "US", "Equinix Inc"),
    ("DLR", "US", "Digital Realty Trust"),
    ("CCI", "US", "Crown Castle"),
    ("SBAC", "US", "SBA Communications"),
    ("WELL", "US", "Welltower Inc"),
    ("O", "US", "Realty Income"),
    ("SPG", "US", "Simon Property Group"),
    ("VICI", "US", "VICI Properties"),
    ("PSA", "US", "Public Storage"),
    ("EXR", "US", "Extra Space Storage"),
    ("AVB", "US", "AvalonBay Communities"),
    ("RSG", "US", "Republic Services"),
    ("WCN", "US", "Waste Connections"),
    ("ROL", "US", "Rollins Inc"),
    ("AXON", "US", "Axon Enterprise"),
    ("TDY", "US", "Teledyne Technologies"),
    # UK
    ("NG.L", "UK", "National Grid"),
    ("SSE.L", "UK", "SSE plc"),
    ("EXPN.L", "UK", "Experian plc"),
    ("REL.L", "UK", "RELX plc"),
    ("SGE.L", "UK", "Sage Group"),
    ("AUTO.L", "UK", "Auto Trader Group"),
    ("IHG.L", "UK", "InterContinental Hotels"),
    ("CPG.L", "UK", "Compass Group"),
    ("TSCO.L", "UK", "Tesco plc"),
    ("AAL.L", "UK", "Anglo American"),
    ("GLEN.L", "UK", "Glencore plc"),
    ("ANTO.L", "UK", "Antofagasta"),
    ("AHT.L", "UK", "Ashtead Group"),
    ("CRDA.L", "UK", "Croda International"),
    ("BNZL.L", "UK", "Bunzl plc"),
    ("RTO.L", "UK", "Rentokil Initial"),
    ("SVT.L", "UK", "Severn Trent"),
    ("UU.L", "UK", "United Utilities"),
    ("SPX.L", "UK", "Spirax-Sarco Engineering"),
    ("HLMA.L", "UK", "Halma plc"),
    ("SMIN.L", "UK", "Smiths Group"),
    ("WEIR.L", "UK", "Weir Group"),
    ("DCC.L", "UK", "DCC plc"),
    ("MNDI.L", "UK", "Mondi plc"),
    # EU
    ("AI.PA", "EU", "Air Liquide"),
    ("SU.PA", "EU", "Schneider Electric"),
    ("BN.PA", "EU", "Danone"),
    ("KER.PA", "EU", "Kering"),
    ("RMS.PA", "EU", "Hermes International"),
    ("EL.PA", "EU", "EssilorLuxottica"),
    ("TTE.PA", "EU", "TotalEnergies"),
    ("DG.PA", "EU", "Vinci SA"),
    ("SGO.PA", "EU", "Saint-Gobain"),
    ("CAP.PA", "EU", "Capgemini"),
    ("DSY.PA", "EU", "Dassault Systemes"),
    ("STMPA.PA", "EU", "STMicroelectronics"),
    ("BMW.DE", "EU", "BMW AG"),
    ("MBG.DE", "EU", "Mercedes-Benz Group"),
    ("ADS.DE", "EU", "Adidas AG"),
    ("BAS.DE", "EU", "BASF SE"),
    ("BAYN.DE", "EU", "Bayer AG"),
    ("MRK.DE", "EU", "Merck KGaA"),
    ("HEN3.DE", "EU", "Henkel AG"),
    ("BEI.DE", "EU", "Beiersdorf AG"),
    ("IFX.DE", "EU", "Infineon Technologies"),
    ("SHL.DE", "EU", "Siemens Healthineers"),
    ("ENR.DE", "EU", "Siemens Energy"),
    ("RWE.DE", "EU", "RWE AG"),
    ("EOAN.DE", "EU", "E.ON SE"),
    ("DPW.DE", "EU", "Deutsche Post DHL"),
    ("FRE.DE", "EU", "Fresenius SE"),
    ("HEI.DE", "EU", "Heidelberg Materials"),
    ("ADYEN.AS", "EU", "Adyen NV"),
    ("PRX.AS", "EU", "Prosus NV"),
    ("WKL.AS", "EU", "Wolters Kluwer"),
    ("ENEL.MI", "EU", "Enel SpA"),
    ("ENI.MI", "EU", "Eni SpA"),
    ("RACE.MI", "EU", "Ferrari NV"),
    ("STLAM.MI", "EU", "Stellantis NV"),
    ("PRY.MI", "EU", "Prysmian SpA"),
    ("MONC.MI", "EU", "Moncler SpA"),
    ("ABBN.SW", "EU", "ABB Ltd"),
    ("SIKA.SW", "EU", "Sika AG"),
    ("GIVN.SW", "EU", "Givaudan SA"),
    ("LONN.SW", "EU", "Lonza Group"),
    ("GEBN.SW", "EU", "Geberit AG"),
    ("CFR.SW", "EU", "Compagnie Financiere Richemont"),
    ("LOGN.SW", "EU", "Logitech International"),
    ("SOON.SW", "EU", "Sonova Holding"),
    ("NOVO-B.CO", "EU", "Novo Nordisk B"),
    ("VWS.CO", "EU", "Vestas Wind Systems"),
    ("DSV.CO", "EU", "DSV A/S"),
    ("ORSTED.CO", "EU", "Orsted A/S"),
    ("GMAB.CO", "EU", "Genmab A/S"),
    ("ATCO-A.ST", "EU", "Atlas Copco A"),
    ("VOLV-B.ST", "EU", "Volvo B"),
    ("ERIC-B.ST", "EU", "Ericsson B"),
    ("SAND.ST", "EU", "Sandvik AB"),
    ("ASSA-B.ST", "EU", "Assa Abloy B"),
    ("HEXA-B.ST", "EU", "Hexagon B"),
    ("ESSITY-B.ST", "EU", "Essity B"),
    ("NOKIA.HE", "EU", "Nokia Oyj"),
    ("KNEBV.HE", "EU", "Kone Oyj"),
    ("UPM.HE", "EU", "UPM-Kymmene"),
    ("ERIC", "US", "Ericsson ADR"),
    ("NOK", "US", "Nokia ADR"),
    ("SAP", "US", "SAP ADR"),
    ("ADDYY", "US", "Adidas ADR"),
    # Japan
    ("6861.T", "APAC", "Keyence Corp"),
    ("8035.T", "APAC", "Tokyo Electron"),
    ("4063.T", "APAC", "Shin-Etsu Chemical"),
    ("6981.T", "APAC", "Murata Manufacturing"),
    ("6501.T", "APAC", "Hitachi Ltd"),
    ("6752.T", "APAC", "Panasonic Holdings"),
    ("9432.T", "APAC", "NTT"),
    ("9433.T", "APAC", "KDDI Corp"),
    ("6367.T", "APAC", "Daikin Industries"),
    ("6273.T", "APAC", "SMC Corp"),
    ("6954.T", "APAC", "Fanuc Corp"),
    ("7741.T", "APAC", "Hoya Corp"),
    ("4519.T", "APAC", "Chugai Pharmaceutical"),
    ("4502.T", "APAC", "Takeda Pharmaceutical"),
    ("4568.T", "APAC", "Daiichi Sankyo"),
    ("6098.T", "APAC", "Recruit Holdings"),
    ("7974.T", "APAC", "Nintendo Co"),
    ("7267.T", "APAC", "Honda Motor"),
    ("6902.T", "APAC", "Denso Corp"),
    ("6594.T", "APAC", "Nidec Corp"),
    ("6920.T", "APAC", "Lasertec Corp"),
    ("6146.T", "APAC", "Disco Corp"),
    ("6857.T", "APAC", "Advantest Corp"),
    ("9983.T", "APAC", "Fast Retailing"),
    ("3382.T", "APAC", "Seven & i Holdings"),
    ("4452.T", "APAC", "Kao Corp"),
    ("4911.T", "APAC", "Shiseido Co"),
    ("4661.T", "APAC", "Oriental Land"),
    ("2802.T", "APAC", "Ajinomoto Co"),
    # Korea / Taiwan
    ("035420.KS", "APAC", "Naver Corp"),
    ("035720.KS", "APAC", "Kakao Corp"),
    ("068270.KS", "APAC", "Celltrion Inc"),
    ("051910.KS", "APAC", "LG Chem"),
    ("006400.KS", "APAC", "Samsung SDI"),
    ("373220.KS", "APAC", "LG Energy Solution"),
    ("005380.KS", "APAC", "Hyundai Motor"),
    ("000270.KS", "APAC", "Kia Corp"),
    ("2454.TW", "APAC", "MediaTek Inc"),
    ("2308.TW", "APAC", "Delta Electronics"),
    ("2382.TW", "APAC", "Quanta Computer"),
    ("3711.TW", "APAC", "ASE Technology"),
    ("2303.TW", "APAC", "United Microelectronics"),
    # Australia
    ("CSL.AX", "APAC", "CSL Ltd"),
    ("WES.AX", "APAC", "Wesfarmers Ltd"),
    ("WTC.AX", "APAC", "WiseTech Global"),
    ("FMG.AX", "APAC", "Fortescue Ltd"),
    ("RIO.AX", "APAC", "Rio Tinto Ltd"),
    ("TLS.AX", "APAC", "Telstra Group"),
    ("TCL.AX", "APAC", "Transurban Group"),
    ("COL.AX", "APAC", "Coles Group"),
    ("JHX.AX", "APAC", "James Hardie"),
    ("COH.AX", "APAC", "Cochlear Ltd"),
    ("XRO.AX", "APAC", "Xero Ltd"),
    ("REA.AX", "APAC", "REA Group"),
    ("NXT.AX", "APAC", "NEXTDC Ltd"),
    # India
    ("WIPRO.NS", "APAC", "Wipro Ltd"),
    ("HCLTECH.NS", "APAC", "HCL Technologies"),
    ("TECHM.NS", "APAC", "Tech Mahindra"),
    ("BHARTIARTL.NS", "APAC", "Bharti Airtel"),
    ("ASIANPAINT.NS", "APAC", "Asian Paints"),
    ("TITAN.NS", "APAC", "Titan Company"),
    ("MARUTI.NS", "APAC", "Maruti Suzuki"),
    ("M&M.NS", "APAC", "Mahindra & Mahindra"),
    ("LT.NS", "APAC", "Larsen & Toubro"),
    ("ULTRACEMCO.NS", "APAC", "UltraTech Cement"),
    ("SUNPHARMA.NS", "APAC", "Sun Pharmaceutical"),
    ("DRREDDY.NS", "APAC", "Dr Reddys Laboratories"),
    ("CIPLA.NS", "APAC", "Cipla Ltd"),
    ("DIVISLAB.NS", "APAC", "Divis Laboratories"),
    ("APOLLOHOSP.NS", "APAC", "Apollo Hospitals"),
    ("HINDUNILVR.NS", "APAC", "Hindustan Unilever"),
    ("NESTLEIND.NS", "APAC", "Nestle India"),
    ("BRITANNIA.NS", "APAC", "Britannia Industries"),
    ("PIDILITIND.NS", "APAC", "Pidilite Industries"),
    ("HAVELLS.NS", "APAC", "Havells India"),
    ("POWERGRID.NS", "APAC", "Power Grid Corp"),
    ("NTPC.NS", "APAC", "NTPC Ltd"),
    ("TATAPOWER.NS", "APAC", "Tata Power"),
    ("JSWSTEEL.NS", "APAC", "JSW Steel"),
    ("HINDALCO.NS", "APAC", "Hindalco Industries"),
    # Greater China / SE Asia
    ("0700.HK", "APAC", "Tencent Holdings"),
    ("9988.HK", "APAC", "Alibaba Group"),
    ("3690.HK", "APAC", "Meituan"),
    ("1810.HK", "APAC", "Xiaomi Corp"),
    ("9618.HK", "APAC", "JD.com"),
    ("1211.HK", "APAC", "BYD Company"),
    ("BABA", "US", "Alibaba ADR"),
    ("PDD", "US", "PDD Holdings"),
    ("JD", "US", "JD.com ADR"),
    ("BIDU", "US", "Baidu ADR"),
    ("TCEHY", "US", "Tencent ADR"),
    ("BYDDY", "US", "BYD ADR"),
    ("SE", "US", "Sea Ltd"),
    ("GRAB", "US", "Grab Holdings"),
    ("CPNG", "US", "Coupang Inc"),
    # LatAm / Canada
    ("NU", "US", "Nu Holdings"),
    ("VALE", "US", "Vale SA ADR"),
    ("SQM", "US", "Sociedad Quimica Minera"),
    ("SCCO", "US", "Southern Copper"),
    ("AMX", "US", "America Movil ADR"),
    ("CX", "US", "Cemex ADR"),
    ("CNI", "US", "Canadian National Railway"),
    ("CP", "US", "Canadian Pacific Kansas City"),
    ("ENB", "US", "Enbridge Inc"),
    ("CNQ", "US", "Canadian Natural Resources"),
    ("SHOP.TO", "CA", "Shopify Inc TSX"),
    ("ATD.TO", "CA", "Alimentation Couche-Tard"),
    ("DOL.TO", "CA", "Dollarama Inc"),
    ("CSU.TO", "CA", "Constellation Software"),
]


def main() -> None:
    seed = {r["ticker"] for r in csv.DictReader(SEED.open(encoding="utf-8"))}
    seen = set(seed)
    rows: list[dict[str, str]] = []
    for ticker, region, name in ADDS:
        if ticker in seen:
            continue
        seen.add(ticker)
        rows.append({"ticker": ticker, "region": region, "name": name})

    with OUT.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=["ticker", "region", "name"])
        writer.writeheader()
        writer.writerows(rows)

    print(f"seed={len(seed)} added={len(rows)} total={len(seed) + len(rows)}")
    print(dict(Counter(r["region"] for r in rows)))


if __name__ == "__main__":
    main()
